### ISSUE TITLE
__init__() missing 1 required positional argument: 'stride'

### ISSUE THREAD

**Issue by 2356852131** [jimitjaishwal/Next-Sequence-Prediction-of-Satellite-Images#1]
Hi!
I was trying out the code，and obtained the error:Traceback (most recent call last):
  File "F:/keyan/code/Next-Sequence-Prediction-of-Satellite-Images-master/test.py", line 28, in <module>
    decoder = Decoder().to(device)
  File "F:\keyan\code\Next-Sequence-Prediction-of-Satellite-Images-master\model.py", line 38, in __init__
    self.up0 = up(160, 80)
TypeError: __init__() missing 1 required positional argument: 'stride'.

I don't know how to solve this problem.
Please help me! Thank you very much!

**Comment by FlyDre** [comment]
> Hi!
> I was trying out the code，and obtained the error:Traceback (most recent call last):
> File "F:/keyan/code/Next-Sequence-Prediction-of-Satellite-Images-master/test.py", line 28, in
> decoder = Decoder().to(device)
> File "F:\keyan\code\Next-Sequence-Prediction-of-Satellite-Images-master\model.py", line 38, in **init**
> self.up0 = up(160, 80)
> TypeError: **init**() missing 1 required positional argument: 'stride'.
> 
> I don't know how to solve this problem.
> Please help me! Thank you very much!

hi there, have you solved this problem? And maybe you could provide me with some advice.

**Comment by agraham9966** [comment]
Hi, 

Did anyone ever manage to figure this issue out?
